# Generated by Django 6.0.3 on 2026-03-13 11:54

from django.db import migrations, models
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Tag = apps.get_model('posts', 'Tag')
    for tag in Tag.objects.all():
        tag.slug = slugify(tag.name)
        tag.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, default=''),
            preserve_default=False,
        ),

        migrations.RunPython(populate_slugs, migrations.RunPython.noop),

        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True, blank=True),
        ),

    ]
